/* rules.js — the ledger. Each rule returns rows {id, group, title, value, limit, verdict: 'pass'|'fail'|'review'|'info', clause, why, fix, levels}.
   Rules read the intent model (project), the level table and the generated plans (plansByKey). Nothing here draws. */
window.Rules = (function () {
  const K = CODES;
  const fmt = (v, d = 1) => (v == null || !isFinite(v) ? '—' : Number(v).toFixed(d).replace(/\.0+$/, ''));
  const m2 = (v) => `${fmt(v, 0)} m²`;

  /* ---------- helpers ---------- */
  function groupPlans(levels, plans) { // identical plan objects (shared cache entries) -> one group with a level range label
    const groups = [];
    for (const L of levels) { const P = plans[L.key]; if (!P) continue; let g = groups.find((x) => x.P === P); if (!g) { g = { P, levels: [] }; groups.push(g); } g.levels.push(L); }
    for (const g of groups) { const n = g.levels.map((l) => l.name); g.label = n.length === 1 ? n[0] : `${n[0]}–${n[n.length - 1]}`; g.count = n.length; }
    return groups;
  }
  function tableLookup(table, n, extraPer, extraFrom) { // [[lo,hi,count],...] with "+1 per extraPer beyond the last row"
    if (!table) return null; let out = 0, last = table[table.length - 1];
    for (const [lo, hi, c] of table) if (n >= lo && n <= hi) return c;
    if (n > last[1]) { out = last[2] + Math.ceil((n - last[1]) / (extraPer || Infinity)); }
    return out;
  }

  /* parking demand estimate from the programme (used by the parking generator before plans exist) */
  function parkingNeed(project) {
    const T = Model.totals(project), res = T.gfa.residential, office = T.gfa.office, retail = T.gfa.retail + T.gfa.restaurant;
    const units = Math.round(res * 0.82 / 68); // avg 68 m² net, 82% efficiency (estimate)
    const mix = K.layout.unitMix, small = units * (mix.studio.share + mix.oneBed.share), mid = units * mix.twoBed.share, big = units * mix.threeBed.share;
    const bikeA = Math.ceil(small * 1.5 + mid * 2.5 + big * 3.0 + office / 170 + retail / 340);
    const bikeB = (units >= 20 ? 2 + Math.floor((units - 20) / 20) : 0) + (office >= 2000 ? 6 : 0) + Math.ceil(retail / 1000);
    const loadingA = (tableLookup(K.parking.loading.residential.A, units, 200) || 0) + (tableLookup(K.parking.loading.office.A, office, 7500) || 0);
    const loadingB = (tableLookup(K.parking.loading.residential.B, units, 200) || 0) + (tableLookup(K.parking.loading.office.B, office, 15000) || 0) + (tableLookup(K.parking.loading.retail.B, retail, 20000) || 0);
    const nonResMax = Math.round((office + retail) / K.parking.vehicle.nonResMaxPer);
    return { units, bikeA, bikeB, loadingA, loadingB, accessibleFraction: 0.05, stallsTarget: null, nonResMax };
  }

  /* ---------- evaluate ---------- */
  const G_inset = (r, m) => ({ x: r.x + m, y: r.y + m, w: r.w - 2 * m, d: r.d - 2 * m });
  const touchesFront = (b, site) => (site.frontage === 'S' && b.y <= 0.3) || (site.frontage === 'N' && b.y + b.d >= site.d - 0.3) || (site.frontage === 'W' && b.x <= 0.3) || (site.frontage === 'E' && b.x + b.w >= site.w - 0.3);
  function polyRectDist(poly, r) { let best = Infinity; const corners = [[r.x, r.y], [r.x + r.w, r.y], [r.x + r.w, r.y + r.d], [r.x, r.y + r.d]]; const segD = (p, a, b) => { const dx = b[0] - a[0], dy = b[1] - a[1], L2 = dx * dx + dy * dy; const t = L2 ? Math.max(0, Math.min(1, ((p[0] - a[0]) * dx + (p[1] - a[1]) * dy) / L2)) : 0; return Math.hypot(p[0] - a[0] - t * dx, p[1] - a[1] - t * dy); };
    for (let i = 0; i < poly.length; i++) { const a = poly[i], b = poly[(i + 1) % poly.length]; for (let k = 0; k < 4; k++) best = Math.min(best, segD(poly[i], corners[k], corners[(k + 1) % 4]), segD(corners[k], a, b)); if (a[0] > r.x && a[0] < r.x + r.w && a[1] > r.y && a[1] < r.y + r.d) best = 0; }
    return best; }
  /* floor area counted toward FSR (the same expressions evaluate() has always used; also used for live feedback while editing) */
  function density(project, T) {
    T = T || Model.totals(project); const siteArea = project.site.w * project.site.d;
    const resFA = T.gfa.residential, amenEx = Math.min(T.gfa.amenity, resFA * K.odp.exclusions.amenityPct);
    const parkAbove = project.blocks.filter((b) => b.use === 'parking').reduce((a, b) => a + Model.slabs(b).filter((z) => z >= -Model.LEVEL_TOL).length * Model.area(b), 0);
    const nonResFA = T.gfa.office + T.gfa.retail + T.gfa.restaurant + (T.gfa.amenity - amenEx) + parkAbove * K.odp.exclusions.parkingAboveGradeCount;
    const fsrFA = resFA + nonResFA, fsr = fsrFA / siteArea;
    return { resFA, amenEx, parkAbove, nonResFA, fsrFA, fsr, siteArea };
  }
  /* ---------- guideline setbacks: site edges with inward normals, and which blocks sit inside a setback line ---------- */
  const SIDE_OF = (nx, ny) => (Math.abs(nx) > Math.abs(ny) ? (nx > 0 ? 'west' : 'east') : (ny > 0 ? 'south' : 'north'));
  function siteEdges(site) {
    const out = [];
    if (site.edges && site.edges.length) { const ring = site.poly || []; const cx = ring.reduce((a, q) => a + q[0] / ring.length, 0), cy = ring.reduce((a, q) => a + q[1] / ring.length, 0);
      for (const e of site.edges) { const dx = e.b[0] - e.a[0], dy = e.b[1] - e.a[1], L = Math.hypot(dx, dy) || 1; let nx = -dy / L, ny = dx / L; if ((cx - e.a[0]) * nx + (cy - e.a[1]) * ny < 0) { nx = -nx; ny = -ny; }
        out.push({ a: e.a, b: e.b, L, nx, ny, kind: e.kind === 's' ? 'street' : e.kind === 'l' ? 'lane' : 'side', name: e.name || '', side: SIDE_OF(nx, ny) }); } return out; }
    const W = site.w, D = site.d, box = { S: { a: [0, 0], b: [W, 0], nx: 0, ny: 1 }, N: { a: [W, D], b: [0, D], nx: 0, ny: -1 }, E: { a: [W, 0], b: [W, D], nx: -1, ny: 0 }, W: { a: [0, D], b: [0, 0], nx: 1, ny: 0 } };
    for (const k of 'SNEW') { const e = box[k]; out.push(Object.assign({ L: Math.hypot(e.b[0] - e.a[0], e.b[1] - e.a[1]), kind: k === (site.frontage || 'S') ? 'street' : k === site.lane ? 'lane' : 'side', name: '', side: { S: 'south', N: 'north', E: 'east', W: 'west' }[k] }, e)); }
    return out;
  }
  /* how far inside the site a rectangle sits from one edge (smallest corner distance along the inward normal); null when the block is beside, not across from, the edge */
  function edgeClearance(rc, e) { const cs = [[rc.x, rc.y], [rc.x + rc.w, rc.y], [rc.x + rc.w, rc.y + rc.d], [rc.x, rc.y + rc.d]]; const tx = (e.b[0] - e.a[0]) / e.L, ty = (e.b[1] - e.a[1]) / e.L; let m = Infinity, u0 = Infinity, u1 = -Infinity;
    for (const [x, y] of cs) { m = Math.min(m, (x - e.a[0]) * e.nx + (y - e.a[1]) * e.ny); const u = (x - e.a[0]) * tx + (y - e.a[1]) * ty; u0 = Math.min(u0, u); u1 = Math.max(u1, u); }
    if (u1 < -0.5 || u0 > e.L + 0.5) return null; return m; }
  function setbackIssues(project, site) {
    const set = (K.odp.guidelineSetbacks || {})[site.setbackSet || 'none']; if (!set || !set.rules.length) return []; const edges = siteEdges(site), out = [];
    for (const b of project.blocks) { if (b.use === 'core' || b.use === 'parking' || b.hidden || Model.blockTop(b) <= 0.1) continue; const rc = window.Form && Form.active(b) ? (() => { const bb = Form.bounds(b, project); return { x: bb.x0, y: bb.y0, w: bb.x1 - bb.x0, d: bb.y1 - bb.y0 }; })() : Model.rect(b); const top = Model.blockTop(b);
      for (const e of edges) { const m = edgeClearance(rc, e); if (m == null) continue; for (const rule of set.rules) { if (rule.edge !== e.kind || rule.buildTo || !(rule.d > 0)) continue; if (top <= rule.above + 0.05) continue; if (m < rule.d - 0.01) out.push({ block: b, edge: e, rule, by: rule.d - m, clear: m }); } } }
    return out.sort((p, q) => q.by - p.by);
  }
  /* the footprint a block may occupy once its top is `top` m: the site box inset by every guideline setback whose height threshold it crosses */
  function setbackBox(site, top) { const box = { x0: 0, y0: 0, x1: site.w, y1: site.d }; const set = (K.odp.guidelineSetbacks || {})[site.setbackSet || 'none']; if (!set || !set.rules.length) return box;
    for (const e of siteEdges(site)) for (const rule of set.rules) { if (rule.edge !== e.kind || rule.buildTo || !(rule.d > 0) || top <= rule.above + 0.05) continue; if (e.side === 'west') box.x0 = Math.max(box.x0, rule.d); else if (e.side === 'east') box.x1 = Math.min(box.x1, site.w - rule.d); else if (e.side === 'south') box.y0 = Math.max(box.y0, rule.d); else if (e.side === 'north') box.y1 = Math.min(box.y1, site.d - rule.d); }
    return box; }
  /* fire separation required between two blocks (Table 3.1.3.1), and whether they touch */
  function fireSeparation(a, b) {
    const grp = (u) => (K.occupancy[u] && K.occupancy[u].group) || null, ga = grp(a.use), gb = grp(b.use), T = (K.fireSep && K.fireSep.table) || {};
    const xy = Model.rectsOverlap(G_inset(Model.rect(a), -0.05), Model.rect(b)), zOv = a.z0 < Model.blockTop(b) + 0.05 && b.z0 < Model.blockTop(a) + 0.05, touch = xy && zOv;
    const stacked = touch && (Math.abs(a.z0 - Model.blockTop(b)) < 0.1 || Math.abs(b.z0 - Model.blockTop(a)) < 0.1), rel = !touch ? 'apart' : stacked ? 'floor' : 'wall';
    if (!ga || !gb) return { ga, gb, hours: null, rel, kind: 'core', note: (K.fireSep && K.fireSep.notes.core) || '' };
    if (ga === gb) return { ga, gb, hours: 0, rel, kind: 'same', note: (K.fireSep && K.fireSep.notes.same) || '' };
    const key = [ga, gb].sort().join('|'); return { ga, gb, hours: T[key] == null ? null : T[key], rel, kind: 'table', key, note: (K.fireSep && K.fireSep.notes[key]) || '' };
  }
  function evaluate(project, plans, levels, ctxData) {
    const rows = [], site = project.site, T = Model.totals(project), siteArea = site.w * site.d;
    const add = (r) => rows.push(Object.assign({ verdict: 'info', limit: '', fix: '', levels: '' }, r));
    const groups = groupPlans(levels, plans);
    const above = groups.filter((g) => g.levels[0].label > 0), below = groups.filter((g) => g.levels[0].label < 0);

    /* ===== Zoning / Downtown ODP ===== */
    const D = K.odp.density[site.densityArea] || {}, H = K.odp.height[site.heightArea] || {};
    const { resFA, amenEx, parkAbove, nonResFA, fsrFA, fsr } = density(project, T);
    if (D.fsr != null) add({ id: 'fsr', group: 'zoning', title: 'Floor space ratio', value: `${fmt(fsr, 2)} FSR · ${m2(fsrFA)} counted`, limit: `max ${fmt(D.fsr, 2)} (area ${site.densityArea})`, verdict: fsr <= D.fsr + 1e-9 ? 'pass' : 'fail', clause: K.odp.density.clause, why: K.odp.density.why, fix: fsr > D.fsr ? `Remove ${m2(fsrFA - D.fsr * siteArea)}: about ${Math.ceil((fsrFA - D.fsr * siteArea) / Math.max(1, T.footprint || 1000))} storeys of the typical plate.` : '' });
    else add({ id: 'fsr', group: 'zoning', title: 'Floor space ratio', value: `${fmt(fsr, 2)} FSR`, limit: D.nonResMax ? `non-residential max ${fmt(D.nonResMax, 2)}` : 'no figure in the ODP for this area', verdict: 'review', clause: K.odp.density.clause, why: K.odp.density.why });
    if (D.dwell === false && resFA > 0) add({ id: 'dwell', group: 'zoning', title: 'Dwelling use', value: `${m2(resFA)} residential`, limit: `not permitted in area ${site.densityArea}`, verdict: 'fail', clause: 'ODP §2, §3(1)', why: 'Some downtown sub-areas (A, B, C1, E, F, K1) exclude new dwelling uses.', fix: 'Change the residential blocks to office or hotel, or pick another sub-area.' });
    if (D.resCap && resFA > 0) { const rf = resFA / siteArea; add({ id: 'rescap', group: 'zoning', title: 'Residential density cap', value: `residential FSR ${fmt(rf, 2)}`, limit: `max ${fmt(D.resCap, 2)}`, verdict: rf <= D.resCap + 1e-9 ? 'pass' : 'fail', clause: 'ODP §3(3)–(4)', why: 'Residential may replace commercial floor area in this sub-area, but never beyond 3.00 FSR.', fix: rf > D.resCap ? `Convert ${m2((rf - D.resCap) * siteArea)} to office or retail.` : '' }); }
    if (D.nonResMin && resFA > 0) { const nf = nonResFA / siteArea; add({ id: 'nonresmin', group: 'zoning', title: 'Minimum non-residential density', value: `non-residential FSR ${fmt(nf, 2)}`, limit: `at least ${fmt(D.nonResMin, 2)} when housing is added`, verdict: nf >= D.nonResMin - 1e-9 ? 'pass' : 'fail', clause: `ODP §3(1) ${site.densityArea}`, why: 'Mixed sub-areas keep a commercial base under new housing.' }); }
    if (D.officeMax) { const of = T.gfa.office / siteArea; add({ id: 'officemax', group: 'zoning', title: 'Office density', value: `office FSR ${fmt(of, 2)}`, limit: `max ${fmt(D.officeMax, 2)}`, verdict: of <= D.officeMax + 1e-9 ? 'pass' : 'fail', clause: `ODP §3(1) ${site.densityArea}`, why: 'Sub-areas G, L1, N and O cap office floor space separately.' }); }
    // height
    const bldgH = T.maxZ; let basic = H.basic, max = H.max, notes = [];
    if (site.heightArea === '1' && (site.tenure === 'rental' || site.tenure === 'social')) { basic = H.rentalOrSocial; notes.push('32.0 m for 100% rental or 67%+ social housing'); }
    if (H.smallSite) { const fr = site.frontage === 'S' || site.frontage === 'N' ? site.w : site.d, need = site.corner ? H.smallSite.corner : H.smallSite.interior; if (fr < need) { basic = site.tenure === 'social' ? H.smallSite.hSocial : H.smallSite.h; notes.push(`${site.corner ? 'corner' : 'interior'} frontage ${fmt(fr)} m is under ${need} m, so the small-site height applies`); } }
    if (H.planes) add({ id: 'height', group: 'zoning', title: 'Height', value: `${fmt(bldgH)} m`, limit: `Figure 1 planes · Board may allow up to ${H.max} m`, verdict: bldgH <= H.max ? 'review' : 'fail', clause: K.odp.height.clause, why: K.odp.height.why });
    else if (basic != null) { const cap = max || basic; const v = bldgH <= basic + 1e-6 ? 'pass' : bldgH <= cap + 1e-6 ? 'review' : 'fail';
      add({ id: 'height', group: 'zoning', title: 'Height', value: `${fmt(bldgH)} m · ${T.storeysAbove} storeys`, limit: `basic ${fmt(basic)} m${max ? `, Board may allow up to ${fmt(max)} m` : ''}`, verdict: v, clause: K.odp.height.clause, why: K.odp.height.why + (notes.length ? ' ' + notes.join('; ') + '.' : ''), fix: v === 'fail' ? `Remove about ${Math.ceil((bldgH - cap) / 3)} storeys, or pursue a rezoning (Higher Buildings Policy).` : v === 'review' ? 'Above the basic height the Board weighs site size, shadow, views, open space and the public realm (§4(3)).' : '' }); }
    if (site.viewConeH != null) add({ id: 'viewcone', group: 'zoning', title: 'Protected public view', value: `${fmt(bldgH)} m`, limit: `view cone limit ${fmt(site.viewConeH)} m at this site`, verdict: bldgH <= site.viewConeH + 1e-6 ? 'pass' : 'fail', clause: K.odp.viewCones.clause, why: K.odp.viewCones.why, fix: bldgH > site.viewConeH ? 'View cones are not discretionary: lower the building or shift it out of the cone.' : '' });
    else if (site.viewCones && site.viewCones.length) add({ id: 'viewcone', group: 'zoning', title: 'Protected public views', value: `view cone${site.viewCones.length > 1 ? 's' : ''} ${site.viewCones.join(', ')} cross this parcel · ${fmt(bldgH)} m proposed`, limit: 'enter the cone height at this site (View Protection Guidelines)', verdict: 'review', clause: K.odp.viewCones.clause, why: K.odp.viewCones.why + ' The cone plane height varies across the site; read it from the guideline sheet for the view and enter it above.' });
    else if (site.parcelIndex != null) add({ id: 'viewcone', group: 'zoning', title: 'Protected public views', value: 'no view cone crosses this parcel', limit: `${K.odp.viewCones.count} protected views from ${K.odp.viewCones.points} points`, verdict: 'pass', clause: K.odp.viewCones.clause, why: K.odp.viewCones.why });
    else add({ id: 'viewcone', group: 'zoning', title: 'Protected public views', value: `${K.odp.viewCones.count} protected views from ${K.odp.viewCones.points} points`, limit: 'pick a parcel on the Site map, or enter the cone height if one crosses the site', verdict: 'review', clause: K.odp.viewCones.clause, why: K.odp.viewCones.why + ' ' + K.odp.viewCones.note });
    if (bldgH > (max || basic || 0) && basic != null) add({ id: 'hbp', group: 'zoning', title: 'Higher Buildings Policy', value: `${fmt(bldgH)} m is above the ODP figure`, limit: `policy band ${K.odp.higherBuildings.band[0]}–${K.odp.higherBuildings.band[1]} m`, verdict: 'review', clause: 'Higher Buildings Policy (1997, under review 2026–27)', why: K.odp.higherBuildings.text });
    if (D.granville || H.granville) add({ id: 'granville', group: 'zoning', title: 'Granville Street Plan', value: `${fmt(bldgH)} m`, limit: `rezoning route ${K.odp.granville.minH}–${K.odp.granville.maxH} m`, verdict: 'review', clause: 'Granville Street Plan, Council 4 Jun 2025', why: K.odp.granville.text });
    if (D.social || site.socialShare > 0 || site.tenure === 'social') add({ id: 'schedj', group: 'zoning', title: 'Social housing · Schedule J', value: site.socialShare > 0 ? `${fmt(site.socialShare * 100, 0)}% social housing` : 'sub-area expects social housing', limit: 'Schedule J of the Zoning and Development By-law', verdict: 'review', clause: 'ODP amendment June 2026', why: K.odp.scheduleJ.text });
    // tower floor plate: Floor-plate bulletin Tables 2–3 by frontage and neighbouring towers (a tower is anything above 18 m)
    const TOWER_H = 18;
    const towerLevels = levels.filter((l) => l.z > TOWER_H - 1e-6 && l.label > 0);
    if (towerLevels.length) { const plates = towerLevels.map((l) => Model.unionArea([...l.blocks.map(Model.rect), ...l.cores.map(Model.rect)])); const maxPlate = Math.max(...plates);
      const fr = site.frontageLen || (site.frontage === 'S' || site.frontage === 'N' ? site.w : site.d), adj = site.adjTowers || 'none';
      let lim, basis;
      if (site.corner) { if (fr < 30) { lim = 0; basis = 'corner frontage under 30 m: not a tower site'; } else if (adj === 'none') { lim = fr < 40 ? 510 : 670; basis = `corner, no tower neighbour, ${fr < 40 ? 'under 40 m' : '40 m or more'} frontage`; } else { lim = fr < 45 ? 370 : 605; basis = `corner with a tower neighbour, ${fr < 45 ? 'under 45 m' : '45 m or more'} frontage`; } }
      else { if (fr < 45) { lim = 0; basis = 'mid-block frontage under 45 m: not a tower site'; } else if (adj === 'none') { lim = 670; basis = 'mid-block, no tower neighbour'; } else if (adj === 'both') { lim = fr < 60 ? 510 : 605; basis = `mid-block between two towers, ${fr < 60 ? 'under 60 m' : '60 m or more'} frontage`; } else { lim = 605; basis = 'mid-block with one tower neighbour'; } }
      if (T.storeysAbove > 40 || (site.tenure === 'social' && fr > 40)) { lim = Math.max(lim, 745); basis += ' · 745 m² allowed over 40 storeys or for social housing on frontage over 40 m'; }
      const v = lim === 0 ? 'fail' : maxPlate <= lim + 1e-6 ? 'pass' : maxPlate <= lim * 1.1 ? 'review' : 'fail';
      add({ id: 'plate', group: 'zoning', title: 'Tower floor plate', value: `${m2(maxPlate)} largest plate above ${TOWER_H} m (cores included)`, limit: lim ? `${lim} m² (${basis})` : basis, verdict: v, clause: 'Floor-plate bulletin Tables 1–3 (Jun 2025); Downtown Design Guidelines', why: 'Downtown limits tower plates by site frontage and neighbouring towers to keep light, views and separation between towers.', fix: v === 'fail' && lim ? `Slim the plate by ${m2(maxPlate - lim)}, or split into two towers 24.4 m apart.` : v === 'review' ? 'Up to 10% over reads as a modest relaxation the Board may accept.' : lim === 0 ? 'Assemble a wider frontage or design a mid-rise.' : '' });
      // tower separation: between on-site towers, and to existing buildings over 18 m within 60 m
      const towers = project.blocks.filter((b) => b.use !== 'core' && !b.hidden && Model.blockTop(b) > TOWER_H + 1e-6 && (b.use === 'residential' || b.use === 'hotel' || b.use === 'office'));
      const pairs = [];
      for (let i = 0; i < towers.length; i++) for (let j = i + 1; j < towers.length; j++) { const a = towers[i], b = towers[j]; if ((a.src || a.id) === (b.src || b.id)) continue; const dx = Math.max(0, Math.max(a.x, b.x) - Math.min(a.x + a.w, b.x + b.w)), dy = Math.max(0, Math.max(a.y, b.y) - Math.min(a.y + a.d, b.y + b.d)); const dsep = Math.hypot(dx, dy); if (!Model.rectsOverlap(a, b)) pairs.push({ a: a.name, b: b.name, d: dsep }); }
      if (ctxData && ctxData.foot) for (const t of towers) for (const f of ctxData.foot) { if (f.h < TOWER_H) continue; const dd = polyRectDist(f.poly, t); if (dd < 60) pairs.push({ a: t.name, b: `existing ${fmt(f.h, 0)} m building`, d: dd, ex: true }); }
      if (pairs.length) { const worst = pairs.reduce((m, p) => (p.d < m.d ? p : m)); add({ id: 'towersep', group: 'zoning', title: 'Tower separation', value: `${fmt(worst.d)} m between ${worst.a} and ${worst.b}${pairs.length > 1 ? ` · ${pairs.length} pairs checked` : ''}`, limit: `${K.odp.setbacks.towerSeparation} m (80 ft) guideline`, verdict: worst.d >= K.odp.setbacks.towerSeparation - 1e-6 ? 'pass' : 'review', clause: 'Downtown Design Guidelines; Higher Buildings norms', why: 'Towers face each other across at least 24.4 m so that windows keep privacy and daylight.', fix: worst.d < K.odp.setbacks.towerSeparation ? 'Slide the tower away from its neighbour.' : '' }); } }
    // daylight to windows (ODP §5)
    if (window.Daylight && project.blocks.some((b) => b.use === 'residential' && !b.hidden)) {
      const cap = (H.max || basic || 91.4);
      /* slices of one sculpted block (form.js) report as that block: worst result, all blockers */
      const dmap = new Map(); for (const r0 of Daylight.evaluate(project, cap)) { const k = r0.block.src || r0.block.id, cur = dmap.get(k), bl = [...new Set([...(cur ? cur.blockers : []), ...r0.blockers])]; if (!cur || r0.worst < cur.worst) dmap.set(k, Object.assign({}, r0, { blockers: bl, worstBand: r0.block.src ? null : r0.worstBand, block: r0.block.src ? Object.assign({}, r0.block, { id: k }) : r0.block })); else cur.blockers = bl; }
      for (const r of dmap.values()) { const pct = Math.round(r.worst * 100); const v = r.worst >= 0.999 ? 'pass' : r.worst >= 0.8 ? 'review' : 'fail';
        add({ id: 'daylight-' + r.block.id, group: 'zoning', title: `Daylight to windows · ${r.block.name}`, value: pct === 100 ? 'every window position sees a clear 50° fan over 24 m' : `${pct}% of window positions on the ${r.worstFace ? r.worstFace.label.toLowerCase() : ''} face clear${r.worstBand ? ` (storeys ${r.worstBand.f0 + 1}–${r.worstBand.f1 + 1})` : ''}${r.blockers.length ? ` · blocked by ${r.blockers.join(', ')}` : ''}`, limit: 'one 50° fan or two fans adding to 70°, clear for 24 m (3.7 m minimum)', verdict: v, clause: 'Downtown ODP §5, Figure 2', why: 'Every habitable window needs a view fan clear of other buildings for 24 m; a neighbour on the shared property line is assumed to build to this site’s own height cap.', fix: v !== 'pass' ? 'Pull the block 24 m off the flank property line, or turn that face into a party wall (no windows).' : '', block: r.block.id }); } }
    // retail continuity (ODP Map 2)
    if (site.retailMap2 && site.retailMap2 !== 'perm') { const ground = levels.find((l) => l.label === 1); const retailLen = ground ? ground.blocks.filter((b) => b.use === 'retail' || b.use === 'restaurant').reduce((a, b) => a + (touchesFront(b, site) ? (site.frontage === 'S' || site.frontage === 'N' ? b.w : b.d) : 0), 0) : 0; const fr2 = site.frontageLen || (site.frontage === 'S' || site.frontage === 'N' ? site.w : site.d); const share = fr2 ? retailLen / fr2 : 0;
      const v = site.retailMap2 === 'req' ? (fr2 - retailLen <= 7.6 ? 'pass' : 'fail') : site.retailMap2 === 'some' ? (fr2 < 22.9 || share >= 0.25 ? 'pass' : 'fail') : (retailLen > 0 ? 'fail' : 'pass');
      add({ id: 'retailmap2', group: 'zoning', title: 'Ground-floor retail on the street', value: `${fmt(retailLen)} of ${fmt(fr2)} m frontage is retail or restaurant (${fmt(share * 100, 0)}%)`, limit: site.retailMap2 === 'req' ? 'continuous retail required: non-retail gaps of 7.6 m (25 ft) or less' : site.retailMap2 === 'some' ? 'some retail required: at least 25% of frontages 22.9 m (75 ft) or longer' : 'ground-floor retail prohibited here (corner-site exception up to 232 m²)', verdict: v, clause: 'ODP §2.1–2.2, Map 2', why: 'Map 2 streets keep the shopping frontages continuous; prohibited streets protect residential ground floors.', fix: v === 'fail' ? (site.retailMap2 === 'proh' ? 'Replace the ground-floor retail with lobby, amenity or homes.' : 'Extend the retail blocks along the street edge.') : '' }); }
    { const set = (K.odp.guidelineSetbacks || {})[site.setbackSet || 'none'], iss = setbackIssues(project, site);
      if (!set || !set.rules.length) add({ id: 'setback', group: 'zoning', title: 'Setbacks', value: 'no numeric yard applies', limit: 'design review', verdict: 'info', clause: K.odp.setbacks.clause, why: K.odp.setbacks.text });
      else add({ id: 'setback', group: 'zoning', title: 'Guideline setbacks', value: iss.length ? iss.slice(0, 4).map((q) => `${q.block.name} crosses the ${q.rule.label} line by ${fmt(q.by, 1)} m (${q.edge.side} side)`).join(' · ') + (iss.length > 4 ? ` · +${iss.length - 4} more` : '') : 'every block clears the guideline setback lines', limit: set.name + ': ' + set.rules.map((q) => q.label).join(', '), verdict: iss.length ? 'review' : 'pass', clause: K.odp.guidelineSetbacks.clause, why: K.odp.guidelineSetbacks.why + ' Source: ' + set.source, fix: iss.length ? `Pull ${iss[0].block.name} ${fmt(iss[0].by, 1)} m away from the ${iss[0].edge.side} line, or set the portion above ${fmt(iss[0].rule.above, 1)} m back.` : '' }); }
    if (ctxData && ctxData.parks && ctxData.parks.length && window.Sun) {
      let any = false;
      for (const park of ctxData.parks) { const cls = Sun.spaceClass(park.name); const r = Sun.parkShadow(park, project, ctxData); if (r.newArea < 1 && !cls) continue; any = true;
        const v = r.newArea < 1 ? 'pass' : cls === 'strict' || cls === 'strict4' || cls === 'sys' ? 'fail' : cls === 'plaza' ? 'review' : 'info';
        add({ id: 'solar-' + park.name, group: 'zoning', title: `Shadow on ${park.name}`, value: r.newArea < 1 ? 'no new shadow 22 Sep 10:00–16:00' : `${m2(r.newArea)} of new shadow at some hour between 10:00 and 16:00 on 22 Sep (${fmt(r.newArea / Math.max(1, r.totalArea) * 100, 0)}% of the park)`, limit: cls ? (cls === 'plaza' ? 'plaza: minimise new shadow' : 'protected park: no new shadow') : 'not on the protected list', verdict: v, clause: `Solar Access Guidelines, adopted ${K.odp.solar.adopted}`, why: K.odp.solar.text + ' Existing 2009 building shadows are subtracted; only shadow the scheme adds counts.', fix: v === 'fail' ? 'Lower or shift the tower away from the park side; use the sun-hour slider to see when the shadow lands.' : '', park: park.name }); }
      if (!any) add({ id: 'solar', group: 'zoning', title: 'Solar access', value: 'no listed park or plaza within 320 m is shaded', limit: 'no new shadow on listed parks', verdict: 'pass', clause: `Solar Access Guidelines, adopted ${K.odp.solar.adopted}`, why: K.odp.solar.text }); }
    else add({ id: 'solar', group: 'zoning', title: 'Solar access', value: K.odp.solar.window, limit: 'no new shadow on listed parks · pick a parcel on the Site map to test it', verdict: 'review', clause: `Solar Access Guidelines, adopted ${K.odp.solar.adopted}`, why: K.odp.solar.text });

    /* ===== Building code: egress ===== */
    add({ id: 'dates', group: 'egress', title: 'By-law in force', value: `VBBL 2025 in force ${K.dates.inForce}`, limit: `in-stream applications until ${K.dates.inStreamUntil}`, verdict: new Date(site.applicationDate) >= new Date(K.dates.inForce) ? 'info' : 'review', clause: 'VBBL No. 14275 transition', why: K.dates.why });
    for (const g of [...above, ...below]) {
      const P = g.P, m = P.metrics, uses = P.tiles.map((t) => t.use), isPark = uses.includes('parking'), isRes = uses.includes('residential'), isD = uses.includes('office');
      const lim = site.sprinklered ? K.travel.sprinkleredAny : isD ? K.travel.groupD : K.travel.other;
      const where = g.label;
      if (m.unreachedRooms || m.unreachedOpenArea) add({ id: `unreached-${P.key}`, group: 'egress', title: `Unreachable exits · ${where}`, value: `${m.unreachedRooms || 0} rooms · ${m2(m.unreachedOpenArea || 0)} open floor without an exit route`, verdict: 'fail', clause: K.travel.clause, why: 'An occupied room or open floor has no traversable route to an exit.', levels: g.levels.map((l) => l.key), plan: P.key });
      if (m.maxTravel > 0) add({ id: `travel-${P.key}`, group: 'egress', title: `Travel distance · ${where}`, value: `${fmt(m.maxTravel)} m to the nearest exit${m.maxTravelRoom ? ` (${m.maxTravelRoom.name})` : ''}`, limit: `max ${lim} m${site.sprinklered && isD ? ' (40 m under 3.4.2.5.(1)(b) read strictly)' : ''}`, verdict: m.maxTravel <= lim ? (site.sprinklered && isD && m.maxTravel > K.travel.groupD ? 'review' : 'pass') : 'fail', clause: K.travel.clause, why: K.travel.why + ' ' + K.travel.measure, fix: m.maxTravel > lim ? 'Add a second core at the far end, or shorten the wing.' : '', levels: g.levels.map((l) => l.key), plan: P.key });
      if (g.levels[0].label > 1 || isPark) {
        const need = m.hasCorridor ? Math.min(m.diagonal / 2, K.exitSeparation.capWithCorridor) : Math.max(m.diagonal / 2, K.exitSeparation.floorNoCorridor);
        const v = m.stairExits < 2 ? 'fail' : m.exitSeparation >= need - 1e-6 ? 'pass' : 'fail';
        add({ id: `sep-${P.key}`, group: 'egress', title: `Exits and separation · ${where}`, value: `${m.stairExits} exit stair door${m.stairExits === 1 ? '' : 's'} · ${fmt(m.exitSeparation)} m apart`, limit: `2 exits · at least ${fmt(need)} m (${m.hasCorridor ? '½ diagonal, capped at 9 m with a public corridor' : '½ diagonal, not less than 9 m'})`, verdict: v, clause: `3.4.2.1.(1); ${K.exitSeparation.clause}`, why: K.exitSeparation.why, fix: v === 'fail' ? (m.stairExits < 2 ? 'Give the core two stairs, or add a second core.' : 'Put the stair doors on opposite core faces, or use a second core.') : '', levels: g.levels.map((l) => l.key), plan: P.key });
      } else add({ id: `sep-${P.key}`, group: 'egress', title: `Exits · ${where}`, value: `${P.exits.filter((e) => e.street).length} street doors · ${m.stairExits} stair doors`, limit: 'exits discharge to the street at grade', verdict: P.exits.some((e) => e.street) || m.stairExits >= 2 ? 'pass' : 'review', clause: '3.4.4.1; 3.4.2.1', why: 'Ground-floor rooms exit directly outside; the tower stairs must also reach the street here.', levels: g.levels.map((l) => l.key), plan: P.key });
      if (m.hasCorridor) add({ id: `dead-${P.key}`, group: 'egress', title: `Dead-end corridor · ${where}`, value: `${fmt(m.deadEnd)} m longest dead end`, limit: `max ${K.deadEnd.max} m`, verdict: m.deadEnd <= K.deadEnd.max + 1e-6 ? 'pass' : 'fail', clause: K.deadEnd.clause, why: K.deadEnd.why, fix: m.deadEnd > K.deadEnd.max ? 'Loop the corridor back to the ring, or add a second core at the end of the wing.' : '', levels: g.levels.map((l) => l.key), plan: P.key });
      // exit width
      const occ = m.occupants || Math.round(m.area / 9.3), perStair = m.stairExits ? Math.ceil(occ / Math.max(2, m.stairExits)) : occ; // each exit counts for at most half
      const reqStair = Math.max(K.widths.stairMinTall, perStair * K.widths.mmPerPersonStair / 1000), reqDoor = Math.max(K.widths.doorMin, perStair * K.widths.mmPerPersonLevel / 1000);
      const stairW = 1.1;
      if (occ > 0 && g.levels[0].label !== 1) add({ id: `width-${P.key}`, group: 'egress', title: `Exit width · ${where}`, value: `${occ} occupants · ${perStair} per stair`, limit: `stair ≥ ${fmt(reqStair, 2)} m (8 mm/person), door ≥ ${fmt(reqDoor, 2)} m (6.1 mm/person)`, verdict: reqStair <= stairW + 1e-6 ? 'pass' : 'review', clause: K.widths.clause, why: K.widths.why + ' Stairs are assumed 1.1 m clear.', fix: reqStair > stairW ? `Widen the stairs to ${fmt(reqStair, 2)} m or reduce the occupant load on this storey.` : '', levels: g.levels.map((l) => l.key), plan: P.key });
      // second egress door for rooms / suites
      const rooms = P.rooms.filter((r) => !r.parent && r.doors && r.doors.length && !['stall', 'aisle', 'ramp', 'open'].includes(r.kind));
      const need2 = rooms.filter((r) => { if (r.use === 'residential') return r.inside > 25 || r.area > 150 * 1.5; const grp = K.occupancy[r.use] ? K.occupancy[r.use].group : 'D'; const lim2 = K.secondDoor[grp] || K.secondDoor.D; return r.doors.length < 2 && (r.area > lim2.area || r.occ > lim2.occ || r.inside > lim2.travel); });
      if (rooms.length) add({ id: `door2-${P.key}`, group: 'egress', title: `Rooms needing a second door · ${where}`, value: need2.length ? `${need2.length} of ${rooms.length}: ${[...new Set(need2.map((r) => r.name))].slice(0, 4).join(', ')}` : `none of ${rooms.length} rooms`, limit: 'one door only if area, load and travel are all under Table 3.3.1.5.-B', verdict: need2.length ? 'fail' : 'pass', clause: K.secondDoor.clause, why: K.secondDoor.why, fix: need2.length ? 'Add a second egress door to the listed rooms, or subdivide them.' : '', levels: g.levels.map((l) => l.key), plan: P.key, rooms: need2.map((r) => r.id) });
      if (isPark) { const clear = g.levels[0].h - 0.45; add({ id: `garage-${P.key}`, group: 'egress', title: `Storage garage · ${where}`, value: `${m.stairExits} exits · ${fmt(clear, 2)} m clear height (${fmt(g.levels[0].h, 1)} m floor to floor less 0.45 m)`, limit: `2 exits · ≥ ${K.storageGarage.clearHeight} m clear · vestibules to tower stairs`, verdict: m.stairExits >= 2 && clear >= K.storageGarage.clearHeight ? 'review' : 'fail', clause: K.storageGarage.clause, why: K.storageGarage.why, levels: g.levels.map((l) => l.key), plan: P.key }); }
    }
    // high building
    const topRes = Math.max(0, ...levels.filter((l) => (l.uses.includes('residential') || l.uses.includes('hotel'))).map((l) => l.z)), topOther = Math.max(0, ...levels.filter((l) => l.label > 0 && !(l.uses.includes('residential') || l.uses.includes('hotel'))).map((l) => l.z));
    const hb = topRes > K.highBuilding.groupCAbove || topOther > K.highBuilding.otherAbove;
    add({ id: 'highbldg', group: 'egress', title: 'High building (3.2.6)', value: `top residential floor ${fmt(topRes)} m · top other floor ${fmt(topOther)} m above grade`, limit: `applies above ${K.highBuilding.groupCAbove} m (Group C) or ${K.highBuilding.otherAbove} m (others)`, verdict: hb ? 'review' : 'pass', clause: K.highBuilding.clause, why: K.highBuilding.why + (hb ? ' Required: ' + K.highBuilding.items.join('; ') + '.' : '') });
    const resStoreys = levels.filter((l) => l.label > 0 && (l.uses.includes('residential') || l.uses.includes('hotel'))).length;
    add({ id: 'singlestair', group: 'egress', title: 'Single exterior exit stair', value: `${resStoreys} residential storeys · ${T.storeysAbove} storeys in all`, limit: `only up to ${K.singleExteriorStair.maxStoreys} storeys, sprinklered, travel ≤ ${K.singleExteriorStair.maxTravel} m`, verdict: T.storeysAbove <= K.singleExteriorStair.maxStoreys && resStoreys > 0 ? 'review' : 'info', clause: K.singleExteriorStair.clause, why: K.singleExteriorStair.text });

    /* ===== Building code: construction and fire separations ===== */
    const resTop = Math.max(0, ...project.blocks.filter((b) => b.use === 'residential' || b.use === 'hotel').map((b) => Model.blockTop(b)));
    const nonCoreAbove = project.blocks.filter((b) => b.use !== 'core' && b.use !== 'parking' && Model.blockTop(b) > 0.1);
    if (nonCoreAbove.length) { const topFloorZ = Math.max(0, ...levels.filter((l) => l.label > 0).map((l) => l.z)); const area = T.footprint || 0; const hasC = project.blocks.some((b) => b.use === 'residential' || b.use === 'hotel');
      let ladder;
      if (hasC) ladder = T.storeysAbove <= 6 && topFloorZ <= 18 && area <= [9000, 4500, 3000, 2250, 1800, 1500][Math.max(0, Math.min(5, T.storeysAbove - 1))] ? ['3.2.2.51', 'combustible (wood frame), 1 h floors'] : T.storeysAbove <= 12 && resTop <= 50 && area <= 6000 ? ['3.2.2.48', 'encapsulated mass timber, up to 12 storeys'] : T.storeysAbove <= 18 && resTop <= 76 && area <= 6000 ? ['3.2.2.93', 'encapsulated mass timber with 70-minute encapsulation, up to 18 storeys'] : ['3.2.2.47', 'noncombustible, 2 h floors'];
      else ladder = T.storeysAbove <= 12 && T.maxZ <= 50 && area <= 7200 ? ['3.2.2.57', 'encapsulated mass timber, up to 12 storeys'] : T.storeysAbove <= 18 && T.maxZ <= 76 ? ['3.2.2.93', 'encapsulated mass timber, up to 18 storeys'] : ['3.2.2.56', 'noncombustible, 2 h floors'];
      add({ id: 'construction', group: 'egress', title: 'Lightest construction permitted', value: `${T.storeysAbove} storeys · top floor ${fmt(topFloorZ)} m · ${m2(area)} building area`, limit: `${ladder[0]}: ${ladder[1]}`, verdict: 'info', clause: `VBBL ${ladder[0]}; 3.2.2.18 sprinklers required`, why: 'The construction article follows storeys, height to the top floor and building area; it sets floor ratings, which the fire separations below depend on.' }); }
    // fire separations between touching or stacked blocks of different occupancy (Table 3.1.3.1)
    const GRP = (u) => (K.occupancy[u] && K.occupancy[u].group) || null;
    const FRR = (K.fireSep && K.fireSep.table) || { 'A-2|C': 1, 'A-2|D': 1, 'A-2|E': 2, 'A-2|F-3': 1, 'C|D': 1, 'C|E': 2, 'C|F-3': 1, 'D|E': 0, 'D|F-3': 0, 'E|F-3': 2 };
    const seps = []; const massBlocks = project.blocks.filter((b) => b.use !== 'core' && !b.hidden);
    for (let i = 0; i < massBlocks.length; i++) for (let j = i + 1; j < massBlocks.length; j++) { const a = massBlocks[i], b = massBlocks[j]; const ga = GRP(a.use), gb = GRP(b.use); if (!ga || !gb || ga === gb) continue;
      const xy = Model.rectsOverlap(G_inset(Model.rect(a), -0.05), Model.rect(b)); const zOv = a.z0 < Model.blockTop(b) + 0.05 && b.z0 < Model.blockTop(a) + 0.05; if (!xy || !zOv) continue;
      const stacked = Math.abs(a.z0 - Model.blockTop(b)) < 0.1 || Math.abs(b.z0 - Model.blockTop(a)) < 0.1; const key = [ga, gb].sort().join('|'); const h = FRR[key]; seps.push({ a, b, h, rel: stacked ? 'floor' : 'wall' }); }
    if (seps.length) { const worst = seps.reduce((m, p) => ((p.h || 0) > (m.h || 0) ? p : m)); add({ id: 'firesep', group: 'egress', title: 'Fire separations between occupancies', value: seps.map((p) => `${p.a.name} / ${p.b.name}: ${p.h ? p.h + ' h' : 'none required'} (${p.rel})`).slice(0, 4).join(' · ') + (seps.length > 4 ? ` · +${seps.length - 4} more` : ''), limit: `Table 3.1.3.1 · highest ${worst.h ? worst.h + ' h' : 'none'}`, verdict: 'info', clause: '3.1.3.1 Table 3.1.3.1; 3.3.4.2 (suites 1 h); 3.4.4.1 (exit enclosures = floor rating, 45 min to 2 h)', why: 'Where two major occupancies meet, the floor or wall between them needs this fire-resistance rating; it drives structure and shaft design.' }); }

    /* ===== Parking By-law 6059 ===== */
    const need = parkingNeed(project), stalls = below.concat(above).reduce((a, g) => a + ((g.P.metrics.parking && g.P.metrics.parking.stalls) || 0) * g.count, 0);
    const acc = below.concat(above).reduce((a, g) => a + ((g.P.metrics.parking && g.P.metrics.parking.accessible) || 0) * g.count, 0);
    const parkGroups = groups.filter((g) => g.P.metrics.parking);
    const nonRes = T.gfa.office + T.gfa.retail + T.gfa.restaurant;
    add({ id: 'pk-count', group: 'parking', title: 'Vehicle parking', value: `${stalls} stalls provided${need.units ? ` · ${need.units} homes (estimate)` : ''}`, limit: `no minimum downtown · non-residential max ${need.nonResMax} (1 per 115 m² of ${m2(nonRes)})${resFA ? ' · no residential maximum' : ''}`, verdict: resFA > 0 || stalls <= need.nonResMax ? 'pass' : 'fail', clause: K.parking.vehicle.clause, why: K.parking.vehicle.why, fix: !resFA && stalls > need.nonResMax ? `Remove ${stalls - need.nonResMax} stalls or a parking level.` : '' });
    const accReq = tableLookup(K.parking.accessible.table, stalls, K.parking.accessible.extraPer) || 0;
    if (stalls) add({ id: 'pk-acc', group: 'parking', title: 'Accessible stalls', value: `${acc} provided`, limit: `at least ${accReq} for ${stalls} stalls · 4.0 × 5.5 m · 2.3 m headroom on the route`, verdict: acc >= accReq ? 'pass' : 'fail', clause: K.parking.accessible.clause, why: K.parking.accessible.why });
    for (const g of parkGroups) { const pm = g.P.metrics.parking, L0 = g.levels[0];
      if (pm.rampLenActual) { const rampW = L0.ramps.length ? Math.min(...L0.ramps.map((r) => r.w)) : 0, needW = stalls >= 20 || (site.streetClass === 'arterial' && stalls >= 10) ? K.parking.ramp.width.local20plus : K.parking.ramp.width.localUnder20;
        add({ id: `pk-ramp-${g.P.key}`, group: 'parking', title: `Ramp · ${g.label}`, value: `${fmt(pm.rampSlope * 100)}% over ${fmt(pm.rampLenActual)} m · ${fmt(rampW)} m wide`, limit: `≤ ${K.parking.ramp.maxSlope * 100}% (needs ${fmt(pm.rampLenNeeded)} m for ${fmt(L0.h)} m drop) · width ≥ ${needW} m`, verdict: pm.rampSlope <= K.parking.ramp.maxSlope + 1e-9 && rampW >= needW - 1e-6 ? 'pass' : 'fail', clause: K.parking.ramp.clause, why: K.parking.ramp.why, fix: pm.rampSlope > K.parking.ramp.maxSlope ? `Lengthen the ramp to ${fmt(pm.rampLenNeeded)} m or lower the parking floor-to-floor.` : rampW < needW ? `Widen the ramp to ${needW} m.` : '', levels: g.levels.map((l) => l.key), plan: g.P.key }); }
      else if (L0.label < 0) add({ id: `pk-ramp-${g.P.key}`, group: 'parking', title: `Ramp · ${g.label}`, value: 'no ramp reaches this level', limit: 'every parking level needs a ramp', verdict: 'fail', clause: K.parking.ramp.clause, why: K.parking.ramp.why, fix: 'Add a ramp (Massing panel) that descends to this level.', levels: g.levels.map((l) => l.key), plan: g.P.key });
      add({ id: `pk-head-${g.P.key}`, group: 'parking', title: `Headroom · ${g.label}`, value: `${fmt(pm.headroom, 2)} m clear (${fmt(L0.h)} m floor to floor less 0.45 m structure and services)`, limit: `≥ ${K.parking.headroom.general} m · ≥ ${K.parking.headroom.accessible} m to accessible stalls`, verdict: pm.headroom >= K.parking.headroom.accessible ? 'pass' : pm.headroom >= K.parking.headroom.general ? 'review' : 'fail', clause: K.parking.headroom.clause, why: K.parking.headroom.why, fix: pm.headroom < K.parking.headroom.accessible ? 'Raise the parking floor-to-floor to 2.75 m clear + structure (about 3.2 m).' : '', levels: g.levels.map((l) => l.key), plan: g.P.key });
      if (pm.unreachableStalls) add({ id: `pk-reach-${g.P.key}`, group: 'parking', title: `Stall access · ${g.label}`, value: `${pm.unreachableStalls} stalls without an aisle`, limit: 'every stall opens onto a drive aisle', verdict: 'fail', clause: K.parking.aisle.clause, why: 'A stall that does not touch an aisle cannot be used.', levels: g.levels.map((l) => l.key), plan: g.P.key });
    }
    const bikeProvided = parkGroups.reduce((a, g) => a + ((g.P.metrics.parking.bikeArea || 0) / 1.8) * g.count, 0);
    add({ id: 'pk-bike', group: 'parking', title: 'Bicycle parking', value: `${Math.floor(bikeProvided)} Class A spaces in bike rooms`, limit: `Class A ≥ ${need.bikeA} · Class B ≥ ${need.bikeB} (racks outside)`, verdict: bikeProvided >= need.bikeA ? 'pass' : 'fail', clause: `${K.parking.bicycle.residential.clause}; ${K.parking.bicycle.office.clause}`, why: K.parking.bicycle.why, fix: bikeProvided < need.bikeA ? `Add ${m2((need.bikeA - bikeProvided) * 1.8)} of bike room on P1 or the ground floor.` : '' });
    const loadRooms = below.filter((g) => g.P.metrics.parking).reduce((a, g) => a + g.P.rooms.filter((r) => r.kind === 'loading').length * g.count, 0) + above.reduce((a, g) => a + g.P.rooms.filter((r) => r.kind === 'loading').length * g.count, 0);
    add({ id: 'pk-load', group: 'parking', title: 'Loading', value: `${loadRooms} bays provided`, limit: `Class A ≥ ${need.loadingA} · Class B ≥ ${need.loadingB} (3.0 × 8.5 m, 3.8 m headroom)`, verdict: loadRooms >= need.loadingA + need.loadingB ? 'pass' : 'fail', clause: `${K.parking.loading.residential.clause}; ${K.parking.loading.office.clause}`, why: K.parking.loading.why, fix: loadRooms < need.loadingA + need.loadingB ? 'Add loading bays off the lane on the ground floor or P1.' : '' });
    if (stalls && resFA) add({ id: 'pk-ev', group: 'parking', title: 'EV charging', value: `${stalls} residential stalls`, limit: 'every residential stall energized', verdict: 'info', clause: K.parking.ev.clause, why: K.parking.ev.text });

    /* ===== Layout advice ===== */
    const resG = above.filter((g) => g.P.metrics.unitsTotal);
    if (resG.length) { const units = resG.reduce((a, g) => a + g.P.metrics.unitsTotal * g.count, 0), fam = resG.reduce((a, g) => a + (g.P.metrics.units['2B'] + g.P.metrics.units['3B']) * g.count, 0) / Math.max(1, units);
      const mix = ['S', '1B', '2B', '3B'].map((t) => `${t} ${resG.reduce((a, g) => a + g.P.metrics.units[t] * g.count, 0)}`).join(' · ');
      add({ id: 'ly-mix', group: 'layout', title: 'Unit mix', value: `${units} homes · ${mix} · ${fmt(fam * 100, 0)}% family`, limit: `about ${K.layout.unitMix.familyShare * 100}% 2- and 3-bedroom (±5)`, verdict: Math.abs(fam - K.layout.unitMix.familyShare) <= 0.05 ? 'pass' : 'review', clause: 'High-Density Housing for Families with Children Guidelines', why: 'Rezonings downtown are expected to deliver about 35% family units; too many large corner suites skew the mix.' });
      const flagsDeep = resG.some((g) => g.P.flags.some((f) => /deeper than/.test(f))); add({ id: 'ly-depth', group: 'layout', title: 'Residential plate depth', value: flagsDeep ? 'unit bands deeper than 13.5 m' : 'unit bands within 13.5 m of the corridor', limit: 'units 9–12 m deep', verdict: flagsDeep ? 'review' : 'pass', clause: 'layout standard', why: K.layout.why });
      const over = resG.some((g) => g.P.flags.some((f) => /corner suite/.test(f))); if (over) add({ id: 'ly-corner', group: 'layout', title: 'Corner suites', value: 'corner suites over 140 m²', limit: 'suites ≤ 140 m²', verdict: 'review', clause: 'layout standard', why: 'The corridor ring does not reach the corner; the end suite absorbs the leftover.', fix: 'Move the core toward the long axis, or add a second core so the ring extends.' }); }
    const offG = above.filter((g) => g.P.metrics.leaseDepth);
    if (offG.length) { const ld = Math.max(...offG.map((g) => g.P.metrics.leaseDepth)); add({ id: 'ly-office', group: 'layout', title: 'Office lease depth', value: `${fmt(ld)} m from core ring to glass`, limit: `${K.layout.plate.officeLeaseDepth[0]}–${K.layout.plate.officeLeaseDepth[1]} m typical, ≤ ${K.layout.plate.officeMaxDepth} m`, verdict: ld <= K.layout.plate.officeLeaseDepth[1] ? 'pass' : ld <= K.layout.plate.officeMaxDepth ? 'review' : 'fail', clause: 'layout standard', why: 'Deep office plates leave desks far from daylight.' }); }
    const retG = above.filter((g) => g.P.metrics.crus);
    if (retG.length) { const bad = retG.some((g) => g.P.flags.some((f) => /narrower|shallower/.test(f))); add({ id: 'ly-retail', group: 'layout', title: 'Retail units', value: `${retG.reduce((a, g) => a + g.P.metrics.crus, 0)} CRUs`, limit: `frontage ${K.layout.plate.retail.frontageMin}–${K.layout.plate.retail.frontageMax} m · depth ≥ ${K.layout.plate.retail.depthMin} m · street exit and rear door`, verdict: bad ? 'review' : 'pass', clause: 'Downtown Design Guidelines 6.2.4(e); leasing standard', why: 'Shopfronts no wider than 9 m keep the street active; shallow units do not lease.' }); }
    const rstG = above.filter((g) => g.P.metrics.bohShare);
    if (rstG.length) { const s = rstG[0].P.metrics.bohShare; add({ id: 'ly-boh', group: 'layout', title: 'Restaurant back of house', value: `${fmt(s * 100, 0)}% of the floor`, limit: `${K.layout.plate.restaurantBOH[0] * 100}–${K.layout.plate.restaurantBOH[1] * 100}%`, verdict: s >= K.layout.plate.restaurantBOH[0] - 0.01 && s <= K.layout.plate.restaurantBOH[1] + 0.01 ? 'pass' : 'review', clause: 'layout standard', why: 'Kitchens, stores and washrooms need about a third of a restaurant.' }); }
    if (stalls) { const parkArea = parkGroups.reduce((a, g) => a + g.P.metrics.area * g.count, 0); add({ id: 'ly-park', group: 'layout', title: 'Parking efficiency', value: `${fmt(parkArea / stalls, 0)} m² per stall`, limit: '30–38 m² per stall is efficient', verdict: parkArea / stalls <= 38 ? 'pass' : 'review', clause: 'layout standard', why: 'Cores, ramps and odd plate shapes eat stalls; above 40 m² per stall the garage is wasting excavation.' }); }
    for (const p of Model.problems(project)) add({ id: 'model-' + p.slice(0, 12), group: 'layout', title: 'Model', value: p, verdict: 'review', clause: '—', why: 'Fix the massing so every block sits inside the site.' });
    return rows;
  }

  return { evaluate, parkingNeed, groupPlans, density, siteEdges, setbackIssues, setbackBox, fireSeparation };
})();
